### PR TITLE
add Map State to schema

### PR DESCRIPTION
**Pull request by Ben-Wormald**
Hi! Thanks for the library, really useful. I've got a PR here to add support for `Map` states.

I couldn't get the new tests to pass locally - I'm getting `Field "x" not allowed in State Machine.States.p.ItemProcessor.States` despite the schema being similar to how the `Parallel` state is defined, as far as I can tell.

Cheers!

### CODE REVIEW

**Comment by jezhiggins** [comment]
Hi Ben,

Thanks for this PR. Please see https://github.com/wmfs/statelint/issues/286#issuecomment-2347193723 but we'll incorporate your change one way or another soon, I hope.

**Comment by Ben-Wormald** [comment]
Hi @jezhiggins that's great, cheers! I do think this PR needs a bit more work, I tried running it against a real schema and was getting the same issue as the tests where the fields inside `States` were not allowed. Not sure what I'm missing there!

**Comment by jezhiggins** [comment]
I think I've found it - there's a bug in the underlying j2119 module

This change in the  Awslabs j2119 isn't reflected in the @wmfs/j2119
https://github.com/awslabs/j2119/blame/master/lib/j2119/node_validator.rb#L59

I suspect if we get that patched up, then there won't need to be any statelint changes beyond the revised schema.

**Comment by jezhiggins** [comment]
PR for j2119 https://github.com/wmfs/j2119/pull/331

**Comment by jezhiggins** [comment]
Hi Ben, 

This PR https://github.com/wmfs/statelint/pull/292 covers your change here, and brings statelint up to date with the current version of ASL, so we can close this. Thanks for raising it though - it's part of what prompted me to get things sorted.

**Comment by Ben-Wormald** [comment]
@jezhiggins brilliant, thanks for working on this

**Pull request closed without merging**
