### PR TITLE
Update to current version of the Amazon State Language

### PR DESCRIPTION
**Pull request by jezhiggins**
This PR syncs up with Amazon State Language as of September 7, 2023

It pulls in the additional tests from (AWSLabs Statelint)[https://github.com/awslabs/statelint] and has the additional supporting code changes too. 

This work also unearthed a bug in j2119, and I've raised a PR for that too - https://github.com/wmfs/j2119/pull/331. 

As I said over on the (issue)[https://github.com/wmfs/statelint/issues/286#issuecomment-2347193723] which prompted me to do this in first place, if accepting this PR would take this package out of sync with statebox and consequently you'd rather not accept it, then that's absolutely fine. I'm happy to fork and release it myself. If, however, you'll accept it, that would be lovely :slightly_smiling_face:

### CODE REVIEW

**Comment by meenahoda** [comment]
Hi @jezhiggins  since you have added the dependency update here then I can close and ignored https://github.com/wmfs/statelint/pull/293

Is this PR ready to be reviewed + merged?

**Comment by jezhiggins** [comment]
Hi Meena,

I think so - the tests all pass - but I'll do another check to confirm everything on the Ruby side is represented here.

Sorry for late response - on a train all day yesterday and out and about in that fancy London now - but will get this sorted out today or tomorrow.

**Comment by jezhiggins** [comment]
Double checked our tests with the [AWS Statelint](https://github.com/awslabs/statelint) and they all line up. In fact, we have a few more, because I've kept some that they've removed.

So yes, we are good to merge :+1:

**Comment by jezhiggins** [comment]
Merging this will also cover the patch in https://github.com/wmfs/statelint/pull/278, which can be closed.

**Comment by meenahoda** [comment]
That's great, thank you for this @jezhiggins  😄

**Pull request merged**
